name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token: # change this
    required: true
    description: 'Github PAT'
  issue-node:
    required: true
    description: 'issue to be put into the project'
  repository:
    required: true
    description: 'the current repo'
runs:
  using: 'node16'
  main: 'dist/index.js'
