name: 'Add issue to project'
description: 'action that fires with new issues, and add the issues to the specified org-level project'
author: 'KittyCAD'
inputs:
  token:
    required: true
    description: 'Github PAT, needs repo and admin:org scope'
  issue-node:
    required: true
    description: 'issue to be put into the project'
  project-number:
    required: false
    description: 'int that appears in project url'
runs:
  using: 'node16'
  main: '../dist/add-issues-to-project/index.js'
