name: 'install-kittycad-cli-action'
description: 'Install KittyCAD CLI on a Linux host'

outputs:
  version:
    description: 'The KittyCAD CLI version that was installed'
    value: ${{ steps.set-output.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: install-kittycad-cli
      if: ${{ runner.os }} == "Linux"
      run: sudo --preserve-env ${{ github.action_path }}/entrypoint.sh
      shell: bash
    - id: install-kittycad-cli-win
      if: ${{ runner.os }} == "Windows"
      run: sudo --preserve-env ${{ github.action_path }}/entrypoint-win.sh
      shell: bash
    - id: set-output
      run: echo "::set-output name=version::$(kittycad --version)"
      shell: bash
