name: 'Update tailscale machine key'
description: 'Action to periodically update a tailscale machine key before expiry'
author: 'KittyCAD'
inputs:
  token:
    required: true
    description: 'Github PAT, needs repo and admin:org scope'
  ts-api-key:
    required: true
    description: 'API key to generate new machine keys'
  current-ts-machine-key:
    required: true
    description: 'Current TS machine key to check for expiry'
  tailnet:
    required: true
    description: 'Tailnet to use for checking/generating keys'
  org-secret-name:
    required: true
    description: 'Org secret to update'
  rotation-lead-time:
    required: false
    default: 7
    description: 'Number of days in advance to rotate a given key'
runs:
  using: 'node16'
  main: '../dist/update-ts-machine-key/index.js'
