name: Add issues to all tasks

on:
  issues:
    types: [opened, reopened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          token: ${{ secrets.GLOBAL_PAT }}
          issue-number: ${{ github.event.issue.id }}"
          repo: ${{ github.event.repository.id }}"
  # test: # make sure the action works on a clean machine without building
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       with:
  #         milliseconds: 1000
