name: Add issues to all tasks

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.token }}
          issue-node: ${{ github.event.issue.node_id }}"
