name: Add issues to all tasks

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  createCard:
    uses: ./
    with:
      token: ${{ secrets.token }}
      issue-node: ${{ github.event.issue.node_id }}"
