name: 'get markdowns repo settings issues'

on:
  pull_request:
    paths:
      - src/check-repo-settings.ts
      - dist/check-repo-settings/**.js
      - .github/workflows/check-repo-settings.yml
      - check-repo-settings/action.yml

jobs:
  weekly-contributions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./check-repo-settings/
        id: check-repo-settings
        with:
          github-token: ${{ secrets.GLOBAL_PAT }}
      - name: setup gh cli
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: comment markdown
        env:
          PRNUM: ${{ github.event.pull_request.number }}
          BODY: '${{ steps.weekly-contributions.outputs.body }}'
        run: gh pr comment $PRNUM --body "$BODY"
