name: "create openapi types"

on:
    pull_request:
      paths:
      - src/create-openapi-types-test.ts
      - dist/create-openapi-types-test/**.js
      - .github/workflows/create-openapi-types-test.yml
      - create-openapi-types-test/action.yml

jobs:
  get-deployment-target-url-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./create-openapi-types/
        with:
          github-token: ${{ secrets.GLOBAL_PAT }}
          repo: api-deux
          spec-path: openapi/api.json
          def-path: spec.ts
      - name: check spec.ts exists
        run: ls -lah
