name: "Show visual-diffs in comment"

on:
    pull_request:

jobs:
  comment-visual-diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./show-visual-diffs-in-comment/
        id: getbody
        with:
          gcloud-credentials-json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}
      - name: setup gh cli
        run: |
            echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: comment diff
        env:
            PRNUM: ${{ github.event.pull_request.number }}
            BODY: ${{ steps.getbody.outputs.body }}
        run: gh pr comment $PRNUM --body "$BODY"
