name: 'get markdowns summary of weekly contributions'
on:
  pull_request:
    paths:
      - src/weekly-contributions.ts
      - dist/weekly-contributions/**.js
      - .github/workflows/weekly-contributions.yml
      - weekly-contributions/action.yml
jobs:
  weekly-contributions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get next date
        id: nextdate
        run: echo "::set-output name=nextdate::$(date --date='+1 day' '+%Y-%m-%d')"
      - uses: ./weekly-contributions/
        id: markdown
        with:
          github-token: ${{ secrets.GLOBAL_PAT }}
          markdown-prefix: "_test prefix_ `code 🤷`"
          login-to-name-map: |
            {
              "alteous": "David Harvey-Macaulay",
              "adamchalmers": "Adam Chalmers",
              "brwhale": "Garrett Skelton",
              "franknoirot": "Frank Noirot",
              "greg-kcio": "Greg Sweeney",
              "gserena01": "Serena Gandhi",
              "hanbollar": "Hannah Bollar",
              "Irev-Dev": "Kurt Hutten",
              "iterion": "Adam Sunderland",
              "JBEmbedded": "Jenna Bryant",
              "jessfraz": "Jess Frazelle",
              "jgomez720": "Josh Gomez",
              "JordanNoone": "Jordan Noone",
              "mansoorsiddiqui": "Mansoor Siddiqui",
              "mlfarrell": "Mike Farrell",
              "pierremtb": "Pierre Jacquier",
              "vonniwilliams": "Vonni Williams"
            }
          ignore-summaries-login-array: |
            [
               "brwhale",
               "hanbollar",
               "JBEmbedded",
               "jessfraz",
               "JordanNoone",
               "mansoorsiddiqui",
               "pierremtb",
               "vonniwilliams"
            ]
      - name: setup gh cli
        run: |
          echo "${{ secrets.GLOBAL_PAT }}" | gh auth login --with-token
      - name: comment markdown
        env:
          PRNUM: ${{ github.event.pull_request.number }}
          BODY: '${{ steps.markdown.outputs.markdown }}'
        run: gh pr comment $PRNUM --body "$BODY"
