name: 'get markdowns summary of weekly contributions'

on:
  pull_request:
    paths:
      - src/weekly-contributions.ts
      - dist/weekly-contributions/**.js
      - .github/workflows/weekly-contributions.yml
      - weekly-contributions/action.yml

jobs:
  weekly-contributions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./weekly-contributions/
        id: weekly-contributions
        with:
          github-token: ${{ secrets.GLOBAL_PAT }}
          markdown-prefix: "_test prefix_ `code 🤷`"
          login-to-name-map: |
              {
                "Irev-Dev": "Kurt",
                "hanbollar": "Hannah",
                "iterion": "Adam",
                "JBEmbedded": "JB",
                "jessfraz": "Jess",
                "jgomez720": "Josh",
                "JordanNoone": "Jordan",
                "mansoorsiddiqui": "Mansoor",
                "vonniwilliams": "Vonni"
              }
          ignore-summaries-login-array: |
              [
                "vonniwilliams",
                "jessfraz"
              ]
      - name: setup gh cli
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: comment markdown
        env:
          PRNUM: ${{ github.event.pull_request.number }}
          BODY: '${{ steps.weekly-contributions.outputs.markdown }}'
        run: gh pr comment $PRNUM --body "$BODY"
